"""Coverage / table catalog constants."""
from __future__ import annotations

from typing import Any

PRIORITY_GROUPS_BASE: list[dict] = [
    {"group": "A_key_financials", "label": "主要会计数据与财务指标",
     "tables": ["key_financials", "non_recurring"], "sections": ["key_financials"]},
    {"group": "B_statements", "label": "三大报表核心科目",
     "tables": ["balance_sheet", "income_stmt", "cashflow_stmt"], "sections": ["balance_sheet", "income_stmt", "cashflow_stmt"]},
    {"group": "C_segments", "label": "主营构成与分部",
     "tables": ["segments", "production_sales"], "sections": ["segments"]},
    {"group": "D_mda", "label": "MD&A 要点",
     "tables": ["variance_reasons", "mda_ratios"],
     "sections": ["mda_overview", "mda_business", "mda_industry", "mda_outlook", "risk_factors"]},
    {"group": "E_holders", "label": "股东与股本", "tables": ["top_holders", "pledge"],
     "sections": ["top_holders", "holder_count", "buyback"]},
    {"group": "F_dividend", "label": "股东回报", "tables": ["dividend"], "sections": ["dividend"]},
    {"group": "G_governance", "label": "治理与人员",
     "tables": ["executives", "employees", "rd_investment", "equity_incentive"],
     "sections": ["executives", "employees"]},
    {"group": "H_matters", "label": "重要事项",
     "tables": ["related_txn", "guarantees"],
     "sections": ["related_txn", "guarantees", "litigation", "commitments", "contingencies", "subsequent"]},
    {"group": "I_audit", "label": "审计与会计政策", "tables": [], "sections": ["audit_report", "key_policies"]},
]

INDUSTRY_EXT_GROUPS: dict[str, dict] = {
    "bank": {"group": "X_bank", "label": "银行业特色（资本充足/资产质量/净息差/存贷款）",
             "keywords": ["资本充足率", "不良贷款", "五级分类", "发放贷款和垫款", "吸收存款", "净息差",
                          "拨备覆盖率", "杠杆率", "净利差"],
             "tables": ["capital_adequacy", "asset_quality", "nim_spread", "deposit_loan"],
             "narratives": ["nim_drivers"],
             "required_gaps": [
                 {"id": "cost_income_ratio", "reason": "成本收入比无专用表，须 text_scan 或标未披露"},
                 {"id": "retail_aum", "reason": "零售/对客 AUM 无专用表，须 text_scan 或标未披露"},
             ]},
    "automobile": {"group": "X_automobile", "label": "汽车制造业特色（产销量/车型分部/新能源）",
                   "keywords": ["产销量", "分车型", "新能源", "销量", "海外", "研发投入"],
                   "tables": ["nev_sales", "capacity_util", "overseas_ops", "production_sales"],
                   "narratives": ["brand_sales", "dealer_network"]},
    "auto_electronics": {
        "group": "X_auto_electronics",
        "label": "智驾/汽车电子方案商特色（分线收入/出货定点/客户集中/研发流片）",
        "keywords": ["自动驾驶", "辅助驾驶", "ADAS", "智能驾驶", "域控制器", "算力", "流片",
                     "定点", "出货量", "车规", "市场份额"],
        "tables": ["ad_shipments", "customer_concentration", "overseas_ops"],
        "narratives": ["design_win_pipeline", "aso_price_trend"],
        "required_gaps": [
            {"id": "market_share_multi_source",
             "reason": "智驾份额三口径（芯片出货/方案装机/收入）无专用表，text_scan 须标口径或标未披露"},
            {"id": "design_win_vs_sop",
             "reason": "定点车型数与 SOP 量产数是两个数，须分行登记，禁止混用"},
        ],
    },
    "manufacturing": {"group": "X_manufacturing", "label": "制造业特色（产销量/产能）",
                      "keywords": ["产销量", "产量", "产能利用率", "产能"]},
    "building_materials": {
        "group": "X_building_materials",
        "label": "建材特色（石膏板/防水/涂料品类产能销量与经销渠道）",
        "keywords": ["石膏板", "防水", "涂料", "产能利用率", "经销", "家装", "工装"],
        "tables": ["capacity_util", "production_sales"],
        "narratives": [],
    },
    "machinery": {
        "group": "X_machinery",
        "label": "机械设备特色（制冷设备/阀件/压缩机品类产销量与产能）",
        "keywords": ["制冷", "压缩机", "换热器", "产销量", "产能利用率", "零部件"],
        "tables": ["capacity_util", "production_sales"],
        "narratives": [],
    },
    "nonferrous": {"group": "X_nonferrous", "label": "有色金属特色（分金属产销量/储量/在建项目/套保成本）",
                   "keywords": ["矿产", "冶炼", "储量", "资源量", "精矿", "套期保值", "在建工程", "产能利用率"],
                   "tables": ["reserves", "construction_projects", "hedging", "production_sales"],
                   "narratives": ["project_progress", "unit_cost"]},
    "insurance": {"group": "X_insurance", "label": "保险业特色（保费/赔付/偿付能力/投资/NBV/渠道）",
                  "keywords": ["保费", "赔付", "退保", "偿付能力", "已赚保费", "承保", "投资资产",
                               "新业务价值", "内含价值", "个险", "银保"],
                  "tables": ["premium_income", "claims_payout", "solvency", "investment_assets",
                             "nbv_ev", "channel_mix"],
                  "narratives": ["underwriting_profit", "spread_income"],
                  # checklist 仍承诺但无 typed 表：materialize 写入 gaps 必答
                  "required_gaps": [
                      {"id": "ifrs17_csm", "reason": "IFRS17 CSM/保险服务业绩若披露须表化或注明未披露"},
                      {"id": "persistency_surrender_rate", "reason": "继续率/退保率时间序列无专用表，须 text_scan 或标未披露"},
                      {"id": "combined_ratio_text",
                       "reason": "综合成本率若仅在正文：text_scan 须 quote+page，或标 not_disclosed"},
                  ]},
    "broker": {"group": "X_broker", "label": "证券业特色（经纪/投行/资管/风控/两融/自营）",
               "keywords": ["经纪业务", "投行", "资管", "净资本", "风险覆盖率", "两融", "客户保证金",
                            "融资融券", "自营"],
               "tables": ["brokerage_income", "ib_underwriting", "am_aum", "risk_indicators",
                          "margin_trading", "prop_trading"],
               "narratives": ["trading_volume_drivers"],
               "required_gaps": [
                   {"id": "client_funds_custody", "reason": "客户资金/托管规模无专用表，须 text_scan 或标未披露"},
               ]},
    "real_estate": {"group": "X_real_estate", "label": "房地产业特色（签约/土储/竣工/合同负债/三道红线）",
                    "keywords": ["签约", "土储", "竣工", "去化", "预售", "销售面积", "合同负债",
                                 "净负债率", "三道红线"],
                    "tables": ["contracted_sales", "land_bank", "delivery_completion",
                               "contract_liabilities", "three_red_lines"],
                    "narratives": ["sell_through", "project_financing"],
                    "required_gaps": [
                        {"id": "land_acquisition", "reason": "拿地金额/面积无专用表，须 text_scan 或标未披露"},
                        {"id": "equity_vs_full_scope", "reason": "权益口径 vs 全口径须在字段 scope 显式标注，混入即 gaps"},
                    ]},
    "energy": {"group": "X_energy", "label": "电力能源特色（装机/发电/利用小时/来水/电价结构）",
               "keywords": ["装机", "发电量", "上网电量", "利用小时", "售电量", "来水", "中长期", "现货"],
               "tables": ["installed_capacity", "power_generation", "utilization_hours",
                          "hydrology", "power_price_mix"],
               "narratives": ["power_price", "fuel_cost"],
               "required_gaps": [
                   {"id": "capacity_under_construction", "reason": "在建装机/外延并购容量无专用表，须 text_scan 或标未披露"},
                   {"id": "controlling_vs_equity_capacity", "reason": "控股 vs 权益装机须在字段 scope 显式标注"},
                   # 表常未晋升时：正文 KPI 不得靠关键词冒充已提取
                   {"id": "installed_capacity_text",
                    "reason": "装机容量若仅在正文：text_scan 须 quote+page，或标 not_disclosed"},
                   {"id": "utilization_hours_text",
                    "reason": "利用小时若仅在正文：text_scan 须 quote+page，或标 not_disclosed"},
                   {"id": "hydrology_text",
                    "reason": "来水/水库若仅在正文：text_scan 须 quote+page，或标 not_disclosed"},
               ]},
    "pharma": {"group": "X_pharma", "label": "制药业特色（管线/渠道/注册准入/GMP产能）",
               "keywords": ["在研", "临床", "集采", "一致性评价", "GMP", "制剂", "仿制药", "创新药"],
               "tables": ["rd_pipeline", "sales_channel_mix", "regulatory_milestones",
                          "capacity_gmp", "production_sales"],
               "narratives": ["pipeline_progress", "vbp_policy_impact"],
               "required_gaps": [
                   {"id": "key_product_pricing",
                    "reason": "核心品种挂网价/中标价/出厂价无专用表，须 text_scan 或标未披露"},
                   {"id": "market_share_estimate",
                    "reason": "市场份额/竞品格局多为估算叙述，须 quote+page 或 not_disclosed"},
                   {"id": "sales_force_scale",
                    "reason": "销售人员/代表人数无专用表，须 text_scan 或标未披露"},
                   {"id": "innovative_vs_generic_mix",
                    "reason": "创新 vs 仿制收入结构若仅正文，须显式 scope 或 not_disclosed"},
                   {"id": "cdmo_order_visibility",
                    "reason": "CDMO/订单能见度无专用表，须 text_scan 或标 not_applicable"},
               ]},
    "consumer": {"group": "X_consumer", "label": "消费零售特色（渠道/经销/门店/同店/产销量）",
                 "keywords": ["经销商", "渠道结构", "同店", "坪效", "门店", "出厂价", "电商渠道"],
                 "tables": ["retail_channel_mix", "dealer_network", "store_operations",
                            "same_store_sales", "production_sales"],
                 "narratives": ["pricing_volume", "channel_reform"],
                 "required_gaps": [
                     {"id": "dealer_inventory",
                      "reason": "渠道库存/社会库存/发货动销无专用表，须 text_scan 或标未披露"},
                     {"id": "same_store_sales_text",
                      "reason": "同店增长若仅在 MD&A：text_scan 须 quote+page，或标 not_disclosed"},
                     {"id": "shipment_vs_revenue",
                      "reason": "发货量/销售额 vs 确认收入须在 scope 显式区分"},
                     {"id": "member_metrics",
                      "reason": "会员数/复购率无专用表，须 text_scan 或标未披露"},
                 ]},
    "transport_infrastructure": {
        "group": "X_transport_infrastructure",
        "label": "交运基建特色（高速通行量/港口吞吐量/路产泊位）",
        "keywords": ["通行量", "通行费", "吞吐量", "集装箱", "泊位", "收费公路"],
        "tables": ["highway_toll_traffic", "concession_network_assets",
                   "port_throughput", "port_berth_assets"],
        "narratives": ["traffic_volume_drivers", "tariff_policy"],
        "required_gaps": [
            {"id": "equity_vs_consolidated_throughput",
             "reason": "权益口径 vs 并表/全口径吞吐量须在字段 scope 显式标注"},
            {"id": "operating_revenue_vs_accounting",
             "reason": "经营收入（通行费/装卸）≠ 会计营业收入，须区分或标未披露"},
            {"id": "concession_remaining_years",
             "reason": "收费年限/特许剩余期限无专用表，须 text_scan 或标未披露"},
            {"id": "capacity_under_construction",
             "reason": "在建路段/泊位无专用表，须 text_scan 或标未披露"},
        ],
        # segment 条件 gaps：materialize 时按 transport_segment 过滤
        "segment_gaps": {
            "highway": [
                {"id": "etc_traffic_mix", "reason": "ETC 占比/车型结构无专用表，须 text_scan 或标未披露"},
                {"id": "toll_per_vehicle_text",
                 "reason": "单车通行费/单公里收入若仅正文：须 quote+page 或 not_disclosed"},
            ],
            "port": [
                {"id": "berth_utilization", "reason": "泊位利用率无专用表，须 text_scan 或标未披露"},
                {"id": "hinterland_economy", "reason": "腹地经济/货源结构无专用表，须 text_scan 或标未披露"},
            ],
        },
    },
    "fossil_energy": {
        "group": "X_fossil_energy",
        "label": "化石能源特色（煤/油气产量、储量、单位成本与价格）",
        "keywords": ["原煤", "商品煤", "吨煤", "原油", "天然气", "油气当量", "证实储量", "长协"],
        "tables": ["coal_production", "coal_reserves", "coal_cost_price",
                   "hydrocarbon_production", "hydrocarbon_reserves", "lifting_cost"],
        "narratives": ["commodity_price", "unit_cost"],
        "required_gaps": [
            {"id": "equity_vs_attributable_output",
             "reason": "权益产量 vs 全口径/并表产量须在 scope 显式标注"},
            {"id": "railway_port_shipment",
             "reason": "铁路/港口外运能力无专用表，须 text_scan 或标未披露"},
            {"id": "coal_washing_yield",
             "reason": "入洗量/洗选率常仅正文，须 text_scan 或标未披露"},
            {"id": "refining_chemical_margin",
             "reason": "炼化/化工毛利无专用表，须 text_scan 或标未披露"},
            {"id": "proved_vs_probable_reserves",
             "reason": "证实/探明/控制分级须分行，不可混加"},
        ],
    },
    # ---- 2025A 新增行业（E3）：最小可用组——表/叙述/缺口按公开披露惯例起步 ----
    "steel": {
        "group": "X_steel", "label": "钢铁业特色（产量/品种结构/吨钢成本）",
        "keywords": ["粗钢", "钢材", "高炉", "吨钢", "螺纹钢"],
        "tables": ["steel_production", "steel_cost_price"],
        "narratives": ["steel_price", "raw_material_cost"],
    },
    "chemicals": {
        "group": "X_chemicals", "label": "化工业特色（品种产能产量/价差）",
        "keywords": ["乙烯", "尿素", "纯碱", "甲醇", "钛白粉"],
        "tables": ["chemical_output", "chemical_price_cost"],
        "narratives": ["product_spread", "feedstock_cost"],
    },
    "telecom": {
        "group": "X_telecom", "label": "通信运营特色（用户/ARPU/网络）",
        "keywords": ["移动用户", "ARPU", "宽带用户", "基站"],
        "tables": ["subscriber_base"],
        "narratives": ["arpu_drivers"],
    },
    "internet_consumer_electronics": {
        "group": "X_internet", "label": "互联网与消费电子特色（MAU/付费/硬件出货）",
        "keywords": ["MAU", "付费用户", "出货量", "IoT"],
        "tables": ["user_metrics", "device_shipments"],
        "narratives": ["user_growth", "hardware_asp"],
    },
    "agriculture": {
        "group": "X_agriculture", "label": "农业特色（出栏存栏/饲料/种植）",
        "keywords": ["生猪", "出栏", "存栏", "饲料", "能繁母猪"],
        "tables": ["livestock_output"],
        "narratives": ["hog_cycle", "feed_cost"],
    },
    "semiconductor": {
        "group": "X_semiconductor", "label": "半导体特色（晶圆产能/制程/良率）",
        "keywords": ["晶圆", "制程", "封测", "良率"],
        "tables": ["wafer_capacity"],
        "narratives": ["fab_capacity_outlook"],
    },
}

NARRATIVE_REQUIRED_IDS = ["mda_business", "mda_industry", "mda_outlook", "risk_factors"]

TABLE_CATALOG: list[dict[str, Any]] = [
    {"table_id": "key_financials", "record_type": "key_financials", "group": "A_key_financials",
     "title": "主要会计数据与财务指标", "description": "摘要表中的关键财务指标"},
    {"table_id": "non_recurring", "record_type": "non_recurring", "group": "A_key_financials",
     "title": "非经常性损益明细", "description": "年报披露的非经常性损益项目"},
    {"table_id": "balance_sheet", "record_type": "balance_sheet", "group": "B_statements",
     "title": "资产负债表", "description": "资产、负债和所有者权益核心科目"},
    {"table_id": "income_stmt", "record_type": "income_stmt", "group": "B_statements",
     "title": "利润表", "description": "营业收入、费用、利润等利润表核心科目"},
    {"table_id": "cashflow_stmt", "record_type": "cashflow_stmt", "group": "B_statements",
     "title": "现金流量表", "description": "经营、投资、筹资活动现金流"},
    {"table_id": "segments_by_industry", "record_type": "segments", "group": "C_segments",
     "title": "分行业主营构成", "description": "分行业维度的收入、成本、毛利率"},
    {"table_id": "segments_by_product", "record_type": "segments", "group": "C_segments",
     "title": "分产品主营构成", "description": "分产品维度的收入、成本、毛利率"},
    {"table_id": "segments_by_region", "record_type": "segments", "group": "C_segments",
     "title": "分地区主营构成", "description": "分地区维度的收入、成本、毛利率"},
    {"table_id": "production_sales", "record_type": "production_sales", "group": "C_segments",
     "title": "产销量与库存", "description": "主要产品的生产量、销售量、库存量"},
    {"table_id": "variance_reasons", "record_type": "variance_reasons", "group": "D_mda",
     "title": "变动原因说明", "description": "同比变动幅度及管理层原因说明"},
    {"table_id": "mda_ratios", "record_type": "mda_ratios", "group": "D_mda",
     "title": "MD&A 比率指标", "description": "毛利率及期间费用占营收比等比率指标"},
    {"table_id": "top_holders", "record_type": "top_holders", "group": "E_holders",
     "title": "前十大股东", "description": "前十大股东及持股比例"},
    {"table_id": "pledge", "record_type": "pledge", "group": "E_holders",
     "title": "股东质押情况", "description": "股东股份质押明细"},
    {"table_id": "dividend", "record_type": "dividend", "group": "F_dividend",
     "title": "分红与股东回报", "description": "利润分配与分红方案"},
    {"table_id": "executives", "record_type": "executives", "group": "G_governance",
     "title": "董事监事与高级管理人员", "description": "董监高姓名、职务、薪酬或持股情况"},
    {"table_id": "employees", "record_type": "employees", "group": "G_governance",
     "title": "员工情况", "description": "员工人数、专业构成与教育程度"},
    {"table_id": "rd_investment", "record_type": "rd_investment", "group": "G_governance",
     "title": "研发投入", "description": "研发费用、资本化金额及占营收比"},
    {"table_id": "equity_incentive", "record_type": "equity_incentive", "group": "G_governance",
     "title": "股权激励", "description": "股权激励或限制性股票计划"},
    {"table_id": "related_txn", "record_type": "related_txn", "group": "H_matters",
     "title": "关联交易", "description": "关联交易金额、定价与关联方"},
    {"table_id": "guarantees", "record_type": "guarantees", "group": "H_matters",
     "title": "对外担保", "description": "对外担保余额与担保对象"},
    {"table_id": "capital_adequacy", "record_type": "capital_adequacy", "group": "X_bank",
     "title": "资本充足率", "description": "核心一级/一级/总资本充足率与杠杆率"},
    {"table_id": "asset_quality", "record_type": "asset_quality", "group": "X_bank",
     "title": "资产质量", "description": "不良贷款率、五级分类、拨备覆盖率与拨贷比"},
    {"table_id": "nim_spread", "record_type": "nim_spread", "group": "X_bank",
     "title": "净息差与净利差", "description": "净息差、净利差及生息资产相关指标"},
    {"table_id": "deposit_loan", "record_type": "deposit_loan", "group": "X_bank",
     "title": "存贷款结构", "description": "吸收存款、发放贷款和垫款余额与结构"},
    {"table_id": "nev_sales", "record_type": "nev_sales", "group": "X_automobile",
     "title": "新能源销量", "description": "新能源车销量及占比"},
    {"table_id": "capacity_util", "record_type": "capacity_util", "group": "X_automobile",
     "title": "产能与利用率", "description": "产能规模及产能利用率"},
    {"table_id": "overseas_ops", "record_type": "overseas_ops", "group": "X_automobile",
     "title": "海外经营", "description": "海外销量或海外收入"},
    {"table_id": "ad_shipments", "record_type": "ad_shipments", "group": "X_auto_electronics",
     "title": "处理硬件出货与均价", "description": "智驾处理硬件出货量与平均售价（ASP）"},
    {"table_id": "customer_concentration", "record_type": "customer_concentration", "group": "X_auto_electronics",
     "title": "客户集中度", "description": "前五大客户收入占比与最大客户占比"},
    {"table_id": "reserves", "record_type": "reserves", "group": "X_nonferrous",
     "title": "资源储量", "description": "矿石量、品位、金属量及储量/资源量分级"},
    {"table_id": "construction_projects", "record_type": "construction_projects", "group": "X_nonferrous",
     "title": "重要在建工程项目", "description": "预算、本期增加、转固、工程累计投入占预算比例与工程进度"},
    {"table_id": "hedging", "record_type": "hedging", "group": "X_nonferrous",
     "title": "衍生品与套期保值", "description": "衍生品合约金额、报告期损益及占净资产比例"},
    {"table_id": "premium_income", "record_type": "premium_income", "group": "X_insurance",
     "title": "保费收入", "description": "原保险保费收入、已赚保费及分险种保费"},
    {"table_id": "claims_payout", "record_type": "claims_payout", "group": "X_insurance",
     "title": "赔付与退保", "description": "赔付支出、退保金等保险给付"},
    {"table_id": "solvency", "record_type": "solvency", "group": "X_insurance",
     "title": "偿付能力", "description": "综合/核心偿付能力充足率及最低资本"},
    {"table_id": "investment_assets", "record_type": "investment_assets", "group": "X_insurance",
     "title": "投资资产结构", "description": "债权、权益及其他投资资产余额与占比"},
    {"table_id": "nbv_ev", "record_type": "nbv_ev", "group": "X_insurance",
     "title": "新业务价值与内含价值", "description": "NBV、NBV margin、内含价值（EV）及变动"},
    {"table_id": "channel_mix", "record_type": "channel_mix", "group": "X_insurance",
     "title": "渠道结构", "description": "个险/银保/经代等渠道保费或价值贡献"},
    {"table_id": "brokerage_income", "record_type": "brokerage_income", "group": "X_broker",
     "title": "经纪业务收入", "description": "代理买卖证券等经纪手续费及佣金"},
    {"table_id": "ib_underwriting", "record_type": "ib_underwriting", "group": "X_broker",
     "title": "投行业务", "description": "承销保荐等投资银行业务收入"},
    {"table_id": "am_aum", "record_type": "am_aum", "group": "X_broker",
     "title": "资产管理", "description": "资管规模与管理费收入"},
    {"table_id": "risk_indicators", "record_type": "risk_indicators", "group": "X_broker",
     "title": "风险控制指标", "description": "净资本、风险覆盖率等监管指标"},
    {"table_id": "margin_trading", "record_type": "margin_trading", "group": "X_broker",
     "title": "融资融券", "description": "两融余额、利息收入或业务规模"},
    {"table_id": "prop_trading", "record_type": "prop_trading", "group": "X_broker",
     "title": "自营与衍生品", "description": "自营投资/权益衍生品损益或规模"},
    {"table_id": "contracted_sales", "record_type": "contracted_sales", "group": "X_real_estate",
     "title": "签约销售", "description": "签约金额、签约面积与销售面积"},
    {"table_id": "land_bank", "record_type": "land_bank", "group": "X_real_estate",
     "title": "土地储备", "description": "土储权益面积与总建筑面积"},
    {"table_id": "delivery_completion", "record_type": "delivery_completion", "group": "X_real_estate",
     "title": "竣工与交付", "description": "竣工面积、交付/结转面积"},
    {"table_id": "contract_liabilities", "record_type": "contract_liabilities", "group": "X_real_estate",
     "title": "合同负债与预收", "description": "合同负债/预收账款余额及与结转收入对照"},
    {"table_id": "three_red_lines", "record_type": "three_red_lines", "group": "X_real_estate",
     "title": "三道红线指标", "description": "净负债率、现金短债比、剔除预收后资产负债率等"},
    {"table_id": "installed_capacity", "record_type": "installed_capacity", "group": "X_energy",
     "title": "装机容量", "description": "分电源装机容量（千瓦/兆瓦）"},
    {"table_id": "power_generation", "record_type": "power_generation", "group": "X_energy",
     "title": "发电与上网电量", "description": "发电量、上网电量、售电量"},
    {"table_id": "utilization_hours", "record_type": "utilization_hours", "group": "X_energy",
     "title": "利用小时", "description": "设备平均利用小时数"},
    {"table_id": "hydrology", "record_type": "hydrology", "group": "X_energy",
     "title": "来水与水库", "description": "来水、水库水位/蓄能或梯级调度相关量"},
    {"table_id": "power_price_mix", "record_type": "power_price_mix", "group": "X_energy",
     "title": "电价与交易结构", "description": "中长期合同 vs 现货/市场化电量占比与电价"},
    {"table_id": "rd_pipeline", "record_type": "rd_pipeline", "group": "X_pharma",
     "title": "研发管线", "description": "在研项目、适应症、临床阶段与累计投入"},
    {"table_id": "sales_channel_mix", "record_type": "sales_channel_mix", "group": "X_pharma",
     "title": "医药销售渠道", "description": "医院/OTC/配送/海外等渠道收入或占比"},
    {"table_id": "regulatory_milestones", "record_type": "regulatory_milestones", "group": "X_pharma",
     "title": "注册与准入里程碑", "description": "注册批件、一致性评价、医保目录、集采中标"},
    {"table_id": "capacity_gmp", "record_type": "capacity_gmp", "group": "X_pharma",
     "title": "GMP 产能", "description": "生产基地、设计产能与产能利用率"},
    {"table_id": "retail_channel_mix", "record_type": "retail_channel_mix", "group": "X_consumer",
     "title": "消费渠道结构", "description": "分渠道销售收入与占比"},
    {"table_id": "dealer_network", "record_type": "dealer_network", "group": "X_consumer",
     "title": "经销商网络", "description": "经销商数量与区域分布"},
    {"table_id": "store_operations", "record_type": "store_operations", "group": "X_consumer",
     "title": "门店运营", "description": "门店新开/关闭与经营面积"},
    {"table_id": "same_store_sales", "record_type": "same_store_sales", "group": "X_consumer",
     "title": "同店销售", "description": "同店增长与坪效"},
    {"table_id": "highway_toll_traffic", "record_type": "highway_toll_traffic", "group": "X_transport_infrastructure",
     "title": "高速通行量与通行费", "description": "分路段通行量、车流量与通行费收入"},
    {"table_id": "concession_network_assets", "record_type": "concession_network_assets", "group": "X_transport_infrastructure",
     "title": "收费路产与特许经营", "description": "收费公路里程、特许经营权与经营期限"},
    {"table_id": "port_throughput", "record_type": "port_throughput", "group": "X_transport_infrastructure",
     "title": "港口吞吐量", "description": "货物/集装箱吞吐量（含 TEU）"},
    {"table_id": "port_berth_assets", "record_type": "port_berth_assets", "group": "X_transport_infrastructure",
     "title": "泊位与港区资产", "description": "泊位数量、港区与码头资产"},
    {"table_id": "coal_production", "record_type": "coal_production", "group": "X_fossil_energy",
     "title": "煤炭产销量", "description": "原煤/商品煤产量、销量与外运量"},
    {"table_id": "coal_reserves", "record_type": "coal_reserves", "group": "X_fossil_energy",
     "title": "煤炭资源储量", "description": "煤炭资源量、可采储量与矿井口径"},
    {"table_id": "coal_cost_price", "record_type": "coal_cost_price", "group": "X_fossil_energy",
     "title": "吨煤成本与煤价", "description": "吨煤成本、长协与市场煤价"},
    {"table_id": "hydrocarbon_production", "record_type": "hydrocarbon_production", "group": "X_fossil_energy",
     "title": "油气产量", "description": "原油、天然气与油气当量产量"},
    {"table_id": "hydrocarbon_reserves", "record_type": "hydrocarbon_reserves", "group": "X_fossil_energy",
     "title": "油气储量", "description": "证实/探明储量与剩余经济可采储量"},
    {"table_id": "lifting_cost", "record_type": "lifting_cost", "group": "X_fossil_energy",
     "title": "桶油成本", "description": "桶油/方气单位操作或完全成本"},
    # ---- 2025A 新增行业表目录（E3）----
    {"table_id": "steel_production", "record_type": "steel_production", "group": "X_steel",
     "title": "钢材产销量", "description": "粗钢/钢材分品种产量、销量与库存"},
    {"table_id": "steel_cost_price", "record_type": "steel_cost_price", "group": "X_steel",
     "title": "吨钢成本与钢价", "description": "吨钢成本、吨钢毛利与分品种售价"},
    {"table_id": "chemical_output", "record_type": "chemical_output", "group": "X_chemicals",
     "title": "化工品产能产量", "description": "主要化工品种产能、产量与开工率"},
    {"table_id": "chemical_price_cost", "record_type": "chemical_price_cost", "group": "X_chemicals",
     "title": "化工品价差与成本", "description": "品种价格、原料成本与价差"},
    {"table_id": "subscriber_base", "record_type": "subscriber_base", "group": "X_telecom",
     "title": "用户数与ARPU", "description": "移动/宽带用户数、净增与 ARPU"},
    {"table_id": "user_metrics", "record_type": "user_metrics", "group": "X_internet",
     "title": "用户与活跃指标", "description": "MAU、付费用户、ARPPU 等用户指标"},
    {"table_id": "device_shipments", "record_type": "device_shipments", "group": "X_internet",
     "title": "硬件出货量", "description": "智能手机/IoT 等硬件出货量与均价"},
    {"table_id": "livestock_output", "record_type": "livestock_output", "group": "X_agriculture",
     "title": "畜禽出栏与存栏", "description": "生猪/禽类出栏量、存栏量与能繁母猪"},
    {"table_id": "wafer_capacity", "record_type": "wafer_capacity", "group": "X_semiconductor",
     "title": "晶圆产能与良率", "description": "折算晶圆产能、制程结构与良率"},
]

TABLE_SPEC_BY_ID = {t["table_id"]: t for t in TABLE_CATALOG}

